###
GET http://localhost:3010/ HTTP/1.1

###
GET http://localhost:3010/users HTTP/1.1

###
GET http://localhost:3010/users/1 HTTP/1.1

###
POST http://localhost:3010/users/register HTTP/1.1
Content-Type: application/json

{   
    "username": "DarioMJ48",
    "password": "1234"
}

###
POST http://localhost:3010/users/login
Content-Type: application/json

{
    "username": "DarioMJ48",
    "password": "1234"
}

###
GET http://localhost:3010/userslogin

###
GET http://localhost:3010/operations HTTP/1.1

###
GET http://localhost:3010/operations/1 HTTP/1.1

###
POST http://localhost:3010/operations/add HTTP/1.1
Content-Type: application/json

{   
    "concept": "Dulce de membrillo",
    "amount": 150,
    "date": "Mon Nov 15,2021",
    "type": "Outflow",
    "category": "Food",
    "UserUserId": 1
}

###
PUT http://localhost:3010/operations/update/1 HTTP/1.1
Content-Type: application/json

{   
    "concept": "Dulce de batata",
    "amount": 250,
    "date": "Fri Dec 15,2021",
    "type": "Outflow",
    "category": "Job"
}

###
DELETE http://localhost:3010/operations/delete/1 HTTP/1.1